### PR TITLE
do not manage permissions of postgres config directory

### PR DESCRIPTION
**Pull request by blbradley**
Reverts #77 and #73.

### CODE REVIEW

**Comment by blbradley** [comment]
Tested on Debian Jessie!

**Comment by blbradley** [comment]
Idempotentcy fails though. Here's the state that runs twice:

```
----------
          ID: postgresql-conf
    Function: file.blockreplace
        Name: /etc/postgresql/9.4/main/postgresql.conf
      Result: True
     Comment: Changes were made
     Started: 09:55:26.367694
    Duration: 2.869 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -615,5 +615,4 @@
                   # Add settings for extensions here
                   # Managed by SaltStack: listen_addresses: please do not edit
                   listen_addresses = '*'
                  -
                   # Managed by SaltStack: end of salt managed zone --
```

**Comment by blbradley** [comment]
Ping @puneetk @gravyboat

**Comment by blbradley** [comment]
test-kitchen run failed on postgres extensions. Probably unrelated.

**Comment by gravyboat** [comment]
Thanks.

**Pull request merged**
