### PR TITLE
Prevent default `fromrepo` being evaluated as string 'None'

### PR DESCRIPTION
**Pull request by myii**
#### Discussion

@noelmcloughlin Thanks for #209; this follows-on from that.

I've been using this formula for some time with `use_upstream_repo: True`.  Didn't have a value for `fromrepo` in the pillar when running this formula for a new minion.  Encountered an error:

```saltstack
          ID: postgresql-server
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit: run-r446ecf8982944cd4a4caa7bf54ad2e02.scope
                    E: The value 'None' is invalid for APT::Default-Release as such a release is not available in the sources
```

Initially tracked back to:

https://github.com/saltstack-formulas/postgres-formula/blob/3d8d8486ed88caa6c93d7a86932daf42fc3977ab/postgres/codenamemap.yaml#L16

* This was being evaluated as `'None'`

Then tracked back to:

https://github.com/saltstack-formulas/postgres-formula/blob/3d8d8486ed88caa6c93d7a86932daf42fc3977ab/postgres/defaults.yaml#L60

* Used debug output of `defaults.postgres` to establish that the bare `fromrepo:` above results in `{..., 'fromrepo': 'None', ...}`

The proposed change in this PR allows `fromrepo` to be evaluated as intended.

---

#### Further potential issues

When collecting the debug output of `defaults.postgres`, the `'None'` strings present correlate with all of the bare defaults:

```python
{
    ...

        'homebrew': {
            'url', 'None',
            'sum': 'None'
        },

    ...

    'fromrepo': 'None',

    ...

    'linux': {
        'altpriority': 'None'
    }
}
```

Appears that it would be appropriate to set default values for these as well, unless there is a specific reason for using `'None'` as a string.

---

#### Consideration: Add `fromrepo` to `pillar.example`

It's probably useful to have `fromrepo` mentioned in `pillar.example`.  Finding an appropriate example value may be difficult.  Was thinking about adding `fromrepo: 'bionic-pgdg'` to this PR but that is Ubuntu-specific.

### CODE REVIEW

**Comment by myii** [comment]
> Would be great if you can update all None to '' & update pillar.example.

@noelmcloughlin Will do that shortly.  My only concern is that `altpriority` appears to be an integer, so the default really should be set to an integer rather than an empty string.  What would be the appropriate value for that?

> Lets use `default` filter like this:
> 
> ```jinja
> {% set fromrepo = repo.fromrepo|default(name ~ '-pgdg', true) %}
> ```

@vutny OK, will apply that to both lines 16 and 41, which are identical.

**Comment by myii** [comment]
@noelmcloughlin @vutny Commits pushed.  I'll also push `pillar.example` soon.  In the meantime, if there is a better suggestion for `altpriority`, I'll modify that and rebase.

**Comment by noelmcloughlin** [comment]
@myii. Just set `altpriority: ''`, thanks.

**Comment by myii** [comment]
@noelmcloughlin OK, added `pillar.example` and rebased to set `altpriority: 0`.  All done from my end.

**Comment by myii** [comment]
@noelmcloughlin Just a thought: should alternatives system be disabled by default?  This won't cause regressions for users?

**Comment by noelmcloughlin** [comment]
Yes, it should be disabled by default - definitely.  8 out of 10 people hate linux alternatives ;-)

**Comment by myii** [comment]
No problem, glad to have been of assistance.

**Pull request merged**
