### PR TITLE
fix(server/init): use `|json` to resolve `2019.2` breaking change

### LINKED ISSUE #253: Unable to locate package on debian stretch
On debian stretch 9.6 if I run the postgres state with defaults, it crash  on postgresql-server with

----------
          ID: postgresql-server
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:

              errors:
                  - Running scope as unit: run-r95b568b09a624343a63bc95286832a39.scope
                    E: Unable to locate package u'postgresql-10'
     Started: 11:51:14.014073
    Duration: 2731.392 ms
     Changes:
----------
It works if i set the package name directly with: 

  pkg: 'postgresql-10'
  pkg_client: 'postgresql-client-10'

### PR DESCRIPTION
**Pull request by myii**
* Close #253:
  - Already tested there

---

Fix confirmation: https://github.com/saltstack-formulas/postgres-formula/issues/253#issuecomment-470860840.

### CODE REVIEW

**Comment by myii** [comment]
Thanks for the review @vutny. Can you merge it as well?

On Wed, 13 Mar 2019 10:24:22 +0000, Denys Havrysh wrote:
> vutny approved this pull request.
>
>
>
>
>

-- 
Sent using Dekko from my Ubuntu device

**Comment by aboe76** [comment]
merged it.

**Comment by myii** [comment]
@aboe76 Thanks.

**Comment by skurfer** [comment]
I think this change also needs to be made in `dev/init.sls` and `client/init.sls`.

**Comment by vutny** [comment]
Good point @skurfer . Would you mind to submit a PR?

**Pull request merged**
