### PR TITLE
Maintain consistent use of `tpldir` (continues from #211)

### PR DESCRIPTION
**Pull request by myii**
Continues work done by @mkotsbak in #211 for files added after that PR was merged.

### CODE REVIEW

**Comment by myii** [comment]
What's the situation with using `tpldir` in `.yaml` files?  I've found that it is in use in the `ceph-formula`:

* https://github.com/saltstack-formulas/ceph-formula/blob/3ee9a548bae5b76a94d06f47a0fddf53a778cdb4/ceph/osmap.yaml#L1
* https://github.com/saltstack-formulas/ceph-formula/blob/3ee9a548bae5b76a94d06f47a0fddf53a778cdb4/ceph/osfamilymap.yaml#L1
* https://github.com/saltstack-formulas/ceph-formula/blob/3ee9a548bae5b76a94d06f47a0fddf53a778cdb4/ceph/codenamemap.yaml#L1

I've tried it out with the `.yaml` files in this repo with no apparent adverse reaction.  If those changes are viable, I can add them to this PR.

**Comment by noelmcloughlin** [comment]
The `tpldir` is just a pattern I saw others using - generally works fine so you could try?

**Comment by noelmcloughlin** [comment]
I never used `salt.file.dirname(tpldir)` pattern - maybe it is exact same as`tmpldir` variable?

**Comment by myii** [comment]
@noelmcloughlin There is a difference between `tpldir` and `salt.file.dirname(tpldir)`.

https://github.com/saltstack/salt/blob/9c81df64c19e1e25cd9cd2be570d116e2a886604/salt/utils/templates.py#L131:

```python
                tpldir = os.path.dirname(template).replace('\\', '/')
```

So this returns the directory name where `template` is located.  That works fine for `.sls` files in the base directory.  But what if the `.sls` file is in a sub-directory, like the ones in this PR?  Using `tpldir` would result in looking for:

* `postgres/client/map.jinja`
* `postgres/dev/map.jinja`
* `postgres/server/map.jinja`

Thus, `salt.file.dirname(tpldir)` is required when an `.sls` file is located within a sub-directory.  This then references the parent directory appropriately, i.e. `postgres/map.jinja`.

Other examples from these same sub-directories:

https://github.com/saltstack-formulas/postgres-formula/blob/d53648249c0b4d09580ba7662bd63d2f9b6e59d9/postgres/client/init.sls#L1

https://github.com/saltstack-formulas/postgres-formula/blob/d53648249c0b4d09580ba7662bd63d2f9b6e59d9/postgres/dev/init.sls#L1

https://github.com/saltstack-formulas/postgres-formula/blob/d53648249c0b4d09580ba7662bd63d2f9b6e59d9/postgres/server/init.sls#L1

**Comment by myii** [comment]
@noelmcloughlin Forgot to mention: thanks for taking the time out to review!

**Comment by aboe76** [comment]
@myii thanks for you work.

**Comment by myii** [comment]
@aboe76 Thanks for the merge.

**Pull request merged**
